name: Train Model
description: Trains a RandomForest model and saves it
inputs:
- name: features_csv
  type: String
- name: labels_csv
  type: String
- name: model_output_path
  type: String
outputs: []
implementation:
  container:
    image: python:3.10
    command: [
      "python3", "pipeline_components/train_model.py",
      "--features_csv", {inputValue: features_csv},
      "--labels_csv", {inputValue: labels_csv},
      "--model_output_path", {inputValue: model_output_path}
    ]